using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GuniKitchen.Models
{

        [Table("Carts")]
        public class Cart
        {

            /// <summary>
            ///     The ID of the Cart
            /// </summary>
            [Display(Name = "Cart ID")]
            [Key]
            [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
            public short Cart_Id { get; set; }

            /// <summary>
            ///     The ID of the User
            /// </summary>

        [Display(Name = "User Id")]
            [Required]
            public short User_Id { get; set; }


        /// <summary>
        ///     The ID of Product
        /// </summary>
        /// 
        [Display(Name = "Product Id")]
        [Required]
        public short Product_Id { get; set; }

        /// <summary>
        ///     The Quantity of Order
        /// </summary>
        /// 

        [Display(Name = "Ordered Quantity")]
        [Required]
        public int Ordered_Quantity { get; set; }


        [Display(Name = "Order Total")]
        [Required]
        public int Order_Total { get; set; }



        [Display(Name = "Payment Type")]
        [Column(TypeName = "varchar(20)")]
        public PaymentTypes Payment_Type { get; set; }


        [Display(Name = "Address")]
        [Required]
        public string Address { get; set; }


        [Display(Name = "Order Status")]
        [Column(TypeName = "varchar(20)")]
        public OrderStatuss Order_Status { get; set; }


        /// <summary>
        ///     The date time stamp when the record was created.
        /// </summary>
        /// <remarks>
        ///     This is marked as a "computed" column, to inform EF that the value for this column
        ///     would be generated by the Database during an INSERT operation, 
        ///     and the developer cannot assign a value to the field.
        ///     
        ///     However, to ensure that this is handled correctly, set the default value 
        ///     in the ApplicationDbContext class during the "OnModelCreating" method.
        /// </remarks>
        [Display(Name = "Ordered At")]
            [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
            public DateTime Ordered_At { get; set; }



           // #region Navigational Properties to the Product Model

            //public ICollection<Product> Products { get; set; }

          //  #endregion

        }

}
